// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientSchedulerProtoc.proto

package com.java.sparrow.protocol;

public final class ClientSchedulerProtoc {
  private ClientSchedulerProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NextMessageTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtocolBuffers.NextMessageType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .ProtocolBuffers.NextMessageType.MessageType type = 1 [default = PROBE_RESPONSE];</code>
     */
    boolean hasType();
    /**
     * <code>required .ProtocolBuffers.NextMessageType.MessageType type = 1 [default = PROBE_RESPONSE];</code>
     */
    com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.MessageType getType();
  }
  /**
   * Protobuf type {@code ProtocolBuffers.NextMessageType}
   */
  public static final class NextMessageType extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtocolBuffers.NextMessageType)
      NextMessageTypeOrBuilder {
    // Use NextMessageType.newBuilder() to construct.
    private NextMessageType(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NextMessageType(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NextMessageType defaultInstance;
    public static NextMessageType getDefaultInstance() {
      return defaultInstance;
    }

    public NextMessageType getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NextMessageType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.MessageType value = com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.java.sparrow.protocol.ClientSchedulerProtoc.internal_static_ProtocolBuffers_NextMessageType_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.java.sparrow.protocol.ClientSchedulerProtoc.internal_static_ProtocolBuffers_NextMessageType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.class, com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.Builder.class);
    }

    public static com.google.protobuf.Parser<NextMessageType> PARSER =
        new com.google.protobuf.AbstractParser<NextMessageType>() {
      public NextMessageType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NextMessageType(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NextMessageType> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code ProtocolBuffers.NextMessageType.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>JOB_BATCH = 0;</code>
       */
      JOB_BATCH(0, 0),
      /**
       * <code>PROBE_RESPONSE = 1;</code>
       */
      PROBE_RESPONSE(1, 1),
      /**
       * <code>WORKER_RESPONSE = 2;</code>
       */
      WORKER_RESPONSE(2, 2),
      /**
       * <code>PROBE = 3;</code>
       */
      PROBE(3, 3),
      /**
       * <code>TASK = 4;</code>
       */
      TASK(4, 4),
      /**
       * <code>HEARTBEAT = 5;</code>
       */
      HEARTBEAT(5, 5),
      ;

      /**
       * <code>JOB_BATCH = 0;</code>
       */
      public static final int JOB_BATCH_VALUE = 0;
      /**
       * <code>PROBE_RESPONSE = 1;</code>
       */
      public static final int PROBE_RESPONSE_VALUE = 1;
      /**
       * <code>WORKER_RESPONSE = 2;</code>
       */
      public static final int WORKER_RESPONSE_VALUE = 2;
      /**
       * <code>PROBE = 3;</code>
       */
      public static final int PROBE_VALUE = 3;
      /**
       * <code>TASK = 4;</code>
       */
      public static final int TASK_VALUE = 4;
      /**
       * <code>HEARTBEAT = 5;</code>
       */
      public static final int HEARTBEAT_VALUE = 5;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return JOB_BATCH;
          case 1: return PROBE_RESPONSE;
          case 2: return WORKER_RESPONSE;
          case 3: return PROBE;
          case 4: return TASK;
          case 5: return HEARTBEAT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ProtocolBuffers.NextMessageType.MessageType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.MessageType type_;
    /**
     * <code>required .ProtocolBuffers.NextMessageType.MessageType type = 1 [default = PROBE_RESPONSE];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ProtocolBuffers.NextMessageType.MessageType type = 1 [default = PROBE_RESPONSE];</code>
     */
    public com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.MessageType getType() {
      return type_;
    }

    private void initFields() {
      type_ = com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.MessageType.PROBE_RESPONSE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtocolBuffers.NextMessageType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtocolBuffers.NextMessageType)
        com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.java.sparrow.protocol.ClientSchedulerProtoc.internal_static_ProtocolBuffers_NextMessageType_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.java.sparrow.protocol.ClientSchedulerProtoc.internal_static_ProtocolBuffers_NextMessageType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.class, com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.Builder.class);
      }

      // Construct using com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.MessageType.PROBE_RESPONSE;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.java.sparrow.protocol.ClientSchedulerProtoc.internal_static_ProtocolBuffers_NextMessageType_descriptor;
      }

      public com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType getDefaultInstanceForType() {
        return com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.getDefaultInstance();
      }

      public com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType build() {
        com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType buildPartial() {
        com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType result = new com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType) {
          return mergeFrom((com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType other) {
        if (other == com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.MessageType type_ = com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.MessageType.PROBE_RESPONSE;
      /**
       * <code>required .ProtocolBuffers.NextMessageType.MessageType type = 1 [default = PROBE_RESPONSE];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ProtocolBuffers.NextMessageType.MessageType type = 1 [default = PROBE_RESPONSE];</code>
       */
      public com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.MessageType getType() {
        return type_;
      }
      /**
       * <code>required .ProtocolBuffers.NextMessageType.MessageType type = 1 [default = PROBE_RESPONSE];</code>
       */
      public Builder setType(com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ProtocolBuffers.NextMessageType.MessageType type = 1 [default = PROBE_RESPONSE];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.java.sparrow.protocol.ClientSchedulerProtoc.NextMessageType.MessageType.PROBE_RESPONSE;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtocolBuffers.NextMessageType)
    }

    static {
      defaultInstance = new NextMessageType(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtocolBuffers.NextMessageType)
  }

  public interface JobBatchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtocolBuffers.JobBatch)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 times_to_execute = 1;</code>
     */
    boolean hasTimesToExecute();
    /**
     * <code>required int32 times_to_execute = 1;</code>
     */
    int getTimesToExecute();

    /**
     * <code>required string task_command = 2;</code>
     */
    boolean hasTaskCommand();
    /**
     * <code>required string task_command = 2;</code>
     */
    java.lang.String getTaskCommand();
    /**
     * <code>required string task_command = 2;</code>
     */
    com.google.protobuf.ByteString
        getTaskCommandBytes();

    /**
     * <code>required int32 task_number = 3;</code>
     */
    boolean hasTaskNumber();
    /**
     * <code>required int32 task_number = 3;</code>
     */
    int getTaskNumber();
  }
  /**
   * Protobuf type {@code ProtocolBuffers.JobBatch}
   */
  public static final class JobBatch extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtocolBuffers.JobBatch)
      JobBatchOrBuilder {
    // Use JobBatch.newBuilder() to construct.
    private JobBatch(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JobBatch(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JobBatch defaultInstance;
    public static JobBatch getDefaultInstance() {
      return defaultInstance;
    }

    public JobBatch getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JobBatch(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timesToExecute_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              taskCommand_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              taskNumber_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.java.sparrow.protocol.ClientSchedulerProtoc.internal_static_ProtocolBuffers_JobBatch_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.java.sparrow.protocol.ClientSchedulerProtoc.internal_static_ProtocolBuffers_JobBatch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch.class, com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch.Builder.class);
    }

    public static com.google.protobuf.Parser<JobBatch> PARSER =
        new com.google.protobuf.AbstractParser<JobBatch>() {
      public JobBatch parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JobBatch(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JobBatch> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TIMES_TO_EXECUTE_FIELD_NUMBER = 1;
    private int timesToExecute_;
    /**
     * <code>required int32 times_to_execute = 1;</code>
     */
    public boolean hasTimesToExecute() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 times_to_execute = 1;</code>
     */
    public int getTimesToExecute() {
      return timesToExecute_;
    }

    public static final int TASK_COMMAND_FIELD_NUMBER = 2;
    private java.lang.Object taskCommand_;
    /**
     * <code>required string task_command = 2;</code>
     */
    public boolean hasTaskCommand() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string task_command = 2;</code>
     */
    public java.lang.String getTaskCommand() {
      java.lang.Object ref = taskCommand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskCommand_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string task_command = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTaskCommandBytes() {
      java.lang.Object ref = taskCommand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskCommand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASK_NUMBER_FIELD_NUMBER = 3;
    private int taskNumber_;
    /**
     * <code>required int32 task_number = 3;</code>
     */
    public boolean hasTaskNumber() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 task_number = 3;</code>
     */
    public int getTaskNumber() {
      return taskNumber_;
    }

    private void initFields() {
      timesToExecute_ = 0;
      taskCommand_ = "";
      taskNumber_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimesToExecute()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTaskCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTaskNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, timesToExecute_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTaskCommandBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, taskNumber_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, timesToExecute_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTaskCommandBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, taskNumber_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtocolBuffers.JobBatch}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtocolBuffers.JobBatch)
        com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.java.sparrow.protocol.ClientSchedulerProtoc.internal_static_ProtocolBuffers_JobBatch_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.java.sparrow.protocol.ClientSchedulerProtoc.internal_static_ProtocolBuffers_JobBatch_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch.class, com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch.Builder.class);
      }

      // Construct using com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timesToExecute_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        taskCommand_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        taskNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.java.sparrow.protocol.ClientSchedulerProtoc.internal_static_ProtocolBuffers_JobBatch_descriptor;
      }

      public com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch getDefaultInstanceForType() {
        return com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch.getDefaultInstance();
      }

      public com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch build() {
        com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch buildPartial() {
        com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch result = new com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timesToExecute_ = timesToExecute_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.taskCommand_ = taskCommand_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.taskNumber_ = taskNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch) {
          return mergeFrom((com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch other) {
        if (other == com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch.getDefaultInstance()) return this;
        if (other.hasTimesToExecute()) {
          setTimesToExecute(other.getTimesToExecute());
        }
        if (other.hasTaskCommand()) {
          bitField0_ |= 0x00000002;
          taskCommand_ = other.taskCommand_;
          onChanged();
        }
        if (other.hasTaskNumber()) {
          setTaskNumber(other.getTaskNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimesToExecute()) {
          
          return false;
        }
        if (!hasTaskCommand()) {
          
          return false;
        }
        if (!hasTaskNumber()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.java.sparrow.protocol.ClientSchedulerProtoc.JobBatch) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int timesToExecute_ ;
      /**
       * <code>required int32 times_to_execute = 1;</code>
       */
      public boolean hasTimesToExecute() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 times_to_execute = 1;</code>
       */
      public int getTimesToExecute() {
        return timesToExecute_;
      }
      /**
       * <code>required int32 times_to_execute = 1;</code>
       */
      public Builder setTimesToExecute(int value) {
        bitField0_ |= 0x00000001;
        timesToExecute_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 times_to_execute = 1;</code>
       */
      public Builder clearTimesToExecute() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timesToExecute_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object taskCommand_ = "";
      /**
       * <code>required string task_command = 2;</code>
       */
      public boolean hasTaskCommand() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string task_command = 2;</code>
       */
      public java.lang.String getTaskCommand() {
        java.lang.Object ref = taskCommand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taskCommand_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string task_command = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTaskCommandBytes() {
        java.lang.Object ref = taskCommand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskCommand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string task_command = 2;</code>
       */
      public Builder setTaskCommand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        taskCommand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string task_command = 2;</code>
       */
      public Builder clearTaskCommand() {
        bitField0_ = (bitField0_ & ~0x00000002);
        taskCommand_ = getDefaultInstance().getTaskCommand();
        onChanged();
        return this;
      }
      /**
       * <code>required string task_command = 2;</code>
       */
      public Builder setTaskCommandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        taskCommand_ = value;
        onChanged();
        return this;
      }

      private int taskNumber_ ;
      /**
       * <code>required int32 task_number = 3;</code>
       */
      public boolean hasTaskNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 task_number = 3;</code>
       */
      public int getTaskNumber() {
        return taskNumber_;
      }
      /**
       * <code>required int32 task_number = 3;</code>
       */
      public Builder setTaskNumber(int value) {
        bitField0_ |= 0x00000004;
        taskNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 task_number = 3;</code>
       */
      public Builder clearTaskNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        taskNumber_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtocolBuffers.JobBatch)
    }

    static {
      defaultInstance = new JobBatch(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtocolBuffers.JobBatch)
  }

  public interface SchedulerResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtocolBuffers.SchedulerResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .ProtocolBuffers.SchedulerResponse.StatusType status = 1 [default = OK];</code>
     */
    boolean hasStatus();
    /**
     * <code>required .ProtocolBuffers.SchedulerResponse.StatusType status = 1 [default = OK];</code>
     */
    com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.StatusType getStatus();
  }
  /**
   * Protobuf type {@code ProtocolBuffers.SchedulerResponse}
   */
  public static final class SchedulerResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtocolBuffers.SchedulerResponse)
      SchedulerResponseOrBuilder {
    // Use SchedulerResponse.newBuilder() to construct.
    private SchedulerResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SchedulerResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SchedulerResponse defaultInstance;
    public static SchedulerResponse getDefaultInstance() {
      return defaultInstance;
    }

    public SchedulerResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SchedulerResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.StatusType value = com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.StatusType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                status_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.java.sparrow.protocol.ClientSchedulerProtoc.internal_static_ProtocolBuffers_SchedulerResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.java.sparrow.protocol.ClientSchedulerProtoc.internal_static_ProtocolBuffers_SchedulerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.class, com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<SchedulerResponse> PARSER =
        new com.google.protobuf.AbstractParser<SchedulerResponse>() {
      public SchedulerResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SchedulerResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SchedulerResponse> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code ProtocolBuffers.SchedulerResponse.StatusType}
     */
    public enum StatusType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OK = 0;</code>
       */
      OK(0, 0),
      /**
       * <code>FAIL = 1;</code>
       */
      FAIL(1, 1),
      ;

      /**
       * <code>OK = 0;</code>
       */
      public static final int OK_VALUE = 0;
      /**
       * <code>FAIL = 1;</code>
       */
      public static final int FAIL_VALUE = 1;


      public final int getNumber() { return value; }

      public static StatusType valueOf(int value) {
        switch (value) {
          case 0: return OK;
          case 1: return FAIL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StatusType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<StatusType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StatusType>() {
              public StatusType findValueByNumber(int number) {
                return StatusType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final StatusType[] VALUES = values();

      public static StatusType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private StatusType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ProtocolBuffers.SchedulerResponse.StatusType)
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.StatusType status_;
    /**
     * <code>required .ProtocolBuffers.SchedulerResponse.StatusType status = 1 [default = OK];</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ProtocolBuffers.SchedulerResponse.StatusType status = 1 [default = OK];</code>
     */
    public com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.StatusType getStatus() {
      return status_;
    }

    private void initFields() {
      status_ = com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.StatusType.OK;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtocolBuffers.SchedulerResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtocolBuffers.SchedulerResponse)
        com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.java.sparrow.protocol.ClientSchedulerProtoc.internal_static_ProtocolBuffers_SchedulerResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.java.sparrow.protocol.ClientSchedulerProtoc.internal_static_ProtocolBuffers_SchedulerResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.class, com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.Builder.class);
      }

      // Construct using com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.StatusType.OK;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.java.sparrow.protocol.ClientSchedulerProtoc.internal_static_ProtocolBuffers_SchedulerResponse_descriptor;
      }

      public com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse getDefaultInstanceForType() {
        return com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.getDefaultInstance();
      }

      public com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse build() {
        com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse buildPartial() {
        com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse result = new com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse) {
          return mergeFrom((com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse other) {
        if (other == com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.StatusType status_ = com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.StatusType.OK;
      /**
       * <code>required .ProtocolBuffers.SchedulerResponse.StatusType status = 1 [default = OK];</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .ProtocolBuffers.SchedulerResponse.StatusType status = 1 [default = OK];</code>
       */
      public com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.StatusType getStatus() {
        return status_;
      }
      /**
       * <code>required .ProtocolBuffers.SchedulerResponse.StatusType status = 1 [default = OK];</code>
       */
      public Builder setStatus(com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.StatusType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .ProtocolBuffers.SchedulerResponse.StatusType status = 1 [default = OK];</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = com.java.sparrow.protocol.ClientSchedulerProtoc.SchedulerResponse.StatusType.OK;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtocolBuffers.SchedulerResponse)
    }

    static {
      defaultInstance = new SchedulerResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtocolBuffers.SchedulerResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtocolBuffers_NextMessageType_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtocolBuffers_NextMessageType_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtocolBuffers_JobBatch_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtocolBuffers_JobBatch_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtocolBuffers_SchedulerResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtocolBuffers_SchedulerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033ClientSchedulerProtoc.proto\022\017ProtocolB" +
      "uffers\"\310\001\n\017NextMessageType\022J\n\004type\030\001 \002(\016" +
      "2,.ProtocolBuffers.NextMessageType.Messa" +
      "geType:\016PROBE_RESPONSE\"i\n\013MessageType\022\r\n" +
      "\tJOB_BATCH\020\000\022\022\n\016PROBE_RESPONSE\020\001\022\023\n\017WORK" +
      "ER_RESPONSE\020\002\022\t\n\005PROBE\020\003\022\010\n\004TASK\020\004\022\r\n\tHE" +
      "ARTBEAT\020\005\"O\n\010JobBatch\022\030\n\020times_to_execut" +
      "e\030\001 \002(\005\022\024\n\014task_command\030\002 \002(\t\022\023\n\013task_nu" +
      "mber\030\003 \002(\005\"v\n\021SchedulerResponse\022A\n\006statu" +
      "s\030\001 \002(\0162-.ProtocolBuffers.SchedulerRespo",
      "nse.StatusType:\002OK\"\036\n\nStatusType\022\006\n\002OK\020\000" +
      "\022\010\n\004FAIL\020\001B2\n\031com.java.sparrow.protocolB" +
      "\025ClientSchedulerProtoc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProtocolBuffers_NextMessageType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtocolBuffers_NextMessageType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtocolBuffers_NextMessageType_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_ProtocolBuffers_JobBatch_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProtocolBuffers_JobBatch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtocolBuffers_JobBatch_descriptor,
        new java.lang.String[] { "TimesToExecute", "TaskCommand", "TaskNumber", });
    internal_static_ProtocolBuffers_SchedulerResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProtocolBuffers_SchedulerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtocolBuffers_SchedulerResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
